language: rust
rust:
  - nightly

addons:
    apt:
        packages:
            # for kcov:
            - binutils-dev
            - libcurl4-openssl-dev
            - libdw-dev
            - libelf-dev

before_script:
    wget 'https://github.com/mikeizbicki/HerbiePlugin/blob/master/data/Herbie.db?raw=true' -O Herbie.db

script:
    cargo test --features=clippy

# copied from https://github.com/hyperium/hyper/blob/d2e9c94cf56c0eb92275557bf3926afeb82e4d3d/.travis.yml#L35
after_success: |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH &&
    travis-cargo coveralls --no-sudo --verify

env:
    global:
        - TRAVIS_CARGO_NIGHTLY_FEATURE=""
